name: Security Check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: System Audit
        run: |
          curl -s http://ifconfig.me
          whoami
          env
